### ISSUE TITLE
show word being looked up and progress indicators

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#15]
on the morph tab we should show a progress indicated and the word/language that was identified while lookup is happening, a status message if the lookup fails. 

Related to https://github.com/alpheios-project/components/issues/65

**Comment by kirlat** [comment]
In an updated version (0.0.26) I added a progress indicator and improved messages to provide more information about state of data. I moved a messages panel to the top, right below a header. I feel that when it is at the bottom, as it was before, important messages can be overlooked easily. Please let me know what do you think about its new location.

I've added some basic messages that I think were missing. If we need to have more or in different wording, please let me know. I tried to follow styles from a webextension to keep code as close to it as possible, but if we decide to stick with a layout like we have now for PWA, we can diverge the PWA code from webextension's and make some bigger improvements.

Right now I don't fully like how messages are shown in a narrow bar and with an empty tab content space (in a situation when data is not available) next to it. It feels incomplete. I'm thinking probably to use a different mechanism for that. Maybe we should show not all messages at once, but rather redirect messages to a tab where they belong. I'm also thinking that if data is not ready yet, we can maybe show on overlay over a corresponding tab content with a progress indicator in it. That would probably indicate clearer that this tab is in a temporary state.

If we retrieve morphological, grammar and inflection data within separate tabs, maybe we should show progress for a morph data retrieval in a morph tab, grammar progress in a grammar tab and so on. As morph tab is opened by default, user will see there a progress indicator related to morph data retrieval only and, when data is obtained, a morph data or some message when morph data is not available. If user decides to switch to a grammar tab while morph data is retrieved, he/she will see a separate progress bar and separate messages related to grammar. I think maybe this way it will be less confusing. It would allow user to focus on the type of data he/she is interested in currently.

I also think that probably we should have some indication of what tab is currently open. Since we have empty space at the header of a panel (it has just menu and close buttons now), maybe we can put a name of a tab along with its icon to the center of it? This will make clear what tab is open. It will also work well with swiping over the header for changing a tab.

I also have some ideas about component improvement as right now it is probably unnecessarily convoluted, but probably it's better to leave till refactoring.

Please let me know what do you think.

**Comment by balmas** [comment]
a few comments:

1. the little debugging panel at the top is very helpful! (Although we will need to be able to disable this via a verbose setting)

2.  I like the progress bar for the messages actually.  Overlays on the tabs which are loading would be good - this is similar to what Harry asked for for the buttons in the webextension in https://github.com/alpheios-project/components/issues/92

3. Agree with the idea of locating progress messages with the ui components for which they are relevant

4. Agree with the suggestion for showing which tab is open

**Comment by kirlat** [comment]
Moving progress messages to the components would required component modifications, in both their templates, probably functions, and data they receive. Modifying existing ones would require webextension changes which probably we should not go into right now.

I think we can create child components in `pwa-prototype` that will inherit from the existing `components` components. This way we would not break `webextension` and can experiment with component updates in `pwa-prototype`. If we'll decide that updated components should be a go, we can transfer changes from them into a `components` library.

Does this sound reasonable?

**Comment by balmas** [comment]
I'm closing this issue for now.  We should open new issues for any refactoring decisions for the future. @kirlat feel free to do that!
