### ISSUE TITLE
use longtap for word selection

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#16]
suggested by @kirlat Taps are used for panning. Since we started to use them for word selection too, I had often word selected when I just wanted to pan a page. Maybe we could use longer taps for word selection and shorter ones for default action (panning)?

**Comment by kirlat** [comment]
I think that also, not counting a tap duration, we should check whether a touch point has moved between touch start and touch end. If it moved, it means that user is moving his/her finger while keeping it pressed against a touch surface, so it's a pan. If there is little or no move, it means that user put his/her finger on a surface and then lifted it, so it's a tap.

What do you think?

**Comment by balmas** [comment]
Yes I think this makes sense

**Comment by kirlat** [comment]
I was experimenting with taps a lot in Chrome DevTools emulator and on Android phone. It seems that a DevTools emulator does not reproduce all device features correctly. Namely, a text selection initiated by a long tap. 

It seems that when tap is longer than 200 ms (approximately), Chrome on Android initiates a text selection with a floating text selection toolbar: https://cdn-images-1.medium.com/max/1600/1*D4zZzPlBTk5cEN9Qn0-cBA.gif This results in a "touchend" event never fired and thus we cannot recognize when a finger was lifted from a surface of a screen. It also seems that iOS does not have this "floating bar" feature (please correct me if I'm wrong).

So it means that we currently cannot track any touches longer than 200 ms with TouchEvents. However, my testing shows that we might not need to.

The problem with previous tap tracking mechanism was that all taps were intercepted and a panel was shown, even if user intent was pan or pinch-zoom. The new version of tracking, however, recognizes both tap duration and a movement between touch start and touch end points. And it seems that with movement recognition we might have no need to restrict tap duration at all. If finger was not moved during a tap (the current threshold is 5 pixels), then this is a tap, and it will select a word and show it in a panel. If finger(s) was(re) moved, then this is pan, pinch-zoom, or a swipe, and there is no need to show a panel. It seems to be working very reliably, and it feels natural to me. To make it even more reliable, we can track number of fingers on a touch surface (should be no more then one for a tap).

To test this whole touchy stuff, I added a test console to the version 0.0.25 of index-dev.html. The purpose of this test console is to show coordinates, movements, and duration of all touch events that we are currently tracking. This is letting us know what the gesture is and what actions it initiates (or not initiates). It also allows to avoid remote debugging which currently has some issues with Service Workers in Chrome.

I've also created four test zones for touch events. They are located closer to the bottom of the page. They track taps of different duration. First one does not have any time restrictions; it tracks all taps that are static (touch start and touch end are very close to each other), no matter what touch duration is. Other three tracks taps with min duration of 125ms, 250ms, and 500ms.

It would be great if you could test different tap variations on different devices and see what would feel most natural for you. Would there be any difference between perception on Android and iOS that we should take into consideration?

Another possibility could be to use Android text selection for selection of a word (instead of using our own selection). It is a standard method of selecting text on Android. It has nice flags that allow to adjust selection boundaries. And we can (probably) add our own items to the floating selection toolbar. However, I feel it is probably more complex to the user than just tapping a word. Also, if text selection process is different on iOS, it might fragment user experience. However, such selection can be useful in complex cases, when user needs to select more than just one word, and we could probably combine both approaches.

Please let me know what do you think about this all. Thanks!

**Comment by kirlat** [comment]
Testing it more I discovered that in DevTools emulator (but not on an Android devices) taps without minimum duration are sometimes confused as word selection actions and that might cause selection of text in menus instead of default menu action. However, I don't see this effect at all on a device. I'm wondering if you will have any experience like that.

If it will cause any issues, we can fight it with setting a min tap duration to 125 ms (or something around that) and/or filtering out taps where selection is empty (but that will not work against selecting text of menu items).

**Comment by balmas** [comment]
In the 0.26 version on my Samsung Galaxy 7 I'm seeing taps of duration anywhere between 45 on the low end and 300 or so on the high end cause the word selection and lookup to occur

**Comment by balmas** [comment]
longer touches (e.g. > 1K) on the Galaxy 7 don't seem to initiate the lookup. They do on the iPad though.

**Comment by balmas** [comment]
Noting ideas from dev call:

- using pointer events when they are available might help with enabling longer tabs on android devices 
- we should highlight the word selected

**Comment by balmas** [comment]
This is working pretty well now.
