### ISSUE TITLE
combine tab icons into a mobile menu when screen is too narrow

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#17]
Suggested by @kirlat All tab icons does not fit a panel on smaller screens. Maybe we can combine them into a mobile menu when screen is too narrow?

**Comment by kirlat** [comment]
Please review an update (version 0.0.21) that transforms a section with tab icons into a mobile menu. It was tricky sometimes, but I was able to do it with the same set of HTML code for both desktop and mobile. I think it should be much simpler this way.

Usually a "hamburger" (3 stripes on top of each other) icon is used as a menu symbol. Since this one was occupied with inflection tables, I used vertical ellipsis for the menu. However, I think maybe it's worth taking a hamburger icon from inflection tables tab and replace it with something, probably "table" (a grid of lines forming a table) for sake of consistency. What do you think?

**Comment by balmas** [comment]
I like it! It works well on my android phone. 
I agree we need to change both the inflection table icon and the grammar icon since these both have other standard meanings.  The original V1 alpheios icons are here: https://github.com/alpheios-project/design-guidelines/tree/master/v1/fficons . I am not at all gifted with svg (as could be seen from my attempt at the tree icon) but maybe we should try recreating them? We used a little table icon for the inflection tables and a quotation mark for the grammar.

**Comment by balmas** [comment]
I will enter issues for those.
