### ISSUE TITLE
add to home screen from child page doesn't use alpheios icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#25]
If you choose to add the device to the home screen from a child content page, the alpheios icon doesn't get used. 
if this is an easy fix I'd like to include it, but if not then it can wait

**Comment by kirlat** [comment]
It's manifest that defines what icon will be used on the home screen. Before, manifest path was incorrect because HtmlWebpackPlugin we're using to inject resources does not use target path to adjust resource paths accordingly.

To provide quick solution, I moved content pages in a dist directory into the root. This should fix the resources path issue.

I tested it on an Android phone, and I was able to add PWA to home screen from a content page. The icon was the correct Alpheios one. Please let me know if it works for you. Thanks!

**Comment by balmas** [comment]
yes it does on both ios and android.
