### ISSUE TITLE
non-vue based inflection table not appearing on Galaxy Note 8

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#48]
@abrasax reports on that on his Galaxy Note 8 the Inflection tables don't appear, just an empty panel. I can't reproduce this on any of my devices. @kirlat can you think of anything that might cause this?

**Comment by abrasax** [comment]
Not a blank screen, but one that just shows the word (eg incol-unt) and
"Noun Declension"  or "Verb Conjugation" with the permutation box.

**Comment by balmas** [comment]
and just a blank space below that? what happens if you scroll or pan down? is it there just not at the top?

**Comment by abrasax** [comment]
Nothing below it. Greek works fine                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Bridget AlmasSent: Thursday, June 7, 2018 3:50 PMTo: alpheios-project/pwa-prototypeReply To: alpheios-project/pwa-prototypeCc: Harry Diakoff; MentionSubject: Re: [alpheios-project/pwa-prototype] inflection tables not appearing? (#48)and just a blank space below that? what happens if you scroll or pan down? is it there just not at the top?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395543541","url":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395543541","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alpheios-project/pwa-prototype","title":"alpheios-project/pwa-prototype","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/alpheios-project/pwa-prototype"}},"updates":{"snippets":[{"icon":"PERSON","message":"@balmas in #48: and just a blank space below that? what happens if you scroll or pan down? is it there just not at the top?"}],"action":{"name":"View Issue","url":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395543541"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [alpheios-project/pwa-prototype] inflection tables not appearing? (#48)",
"sections": [
{
"text": "",
"activityTitle": "**Bridget Almas**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@balmas",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"alpheios-project/pwa-prototype\",\n\"issueId\": 48,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"alpheios-project/pwa-prototype\",\n\"issueId\": 48\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395543541"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343670945\n}"
}
],
"themeColor": "26292E"
}

**Comment by balmas** [comment]
that is bizarre. Do Greek nouns as well as verbs work?

**Comment by abrasax** [comment]
No - the greek nouns fail                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Bridget AlmasSent: Thursday, June 7, 2018 3:52 PMTo: alpheios-project/pwa-prototypeReply To: alpheios-project/pwa-prototypeCc: Harry Diakoff; MentionSubject: Re: [alpheios-project/pwa-prototype] inflection tables not appearing? (#48)that is bizarre. Do Greek nouns as well as verbs work?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106","url":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alpheios-project/pwa-prototype","title":"alpheios-project/pwa-prototype","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/alpheios-project/pwa-prototype"}},"updates":{"snippets":[{"icon":"PERSON","message":"@balmas in #48: that is bizarre. Do Greek nouns as well as verbs work?"}],"action":{"name":"View Issue","url":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [alpheios-project/pwa-prototype] inflection tables not appearing? (#48)",
"sections": [
{
"text": "",
"activityTitle": "**Bridget Almas**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@balmas",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"alpheios-project/pwa-prototype\",\n\"issueId\": 48,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"alpheios-project/pwa-prototype\",\n\"issueId\": 48\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343670945\n}"
}
],
"themeColor": "26292E"
}

**Comment by balmas** [comment]
ah, okay this is very helpful. the Greek Verbs use a different (newer) component than the other inflection tables do, so it must be something with that older component that is not working for your display. We will investigate.

**Comment by abrasax** [comment]
But in Latin it's both nouns and verbs that fail                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Bridget AlmasSent: Thursday, June 7, 2018 3:52 PMTo: alpheios-project/pwa-prototypeReply To: alpheios-project/pwa-prototypeCc: Harry Diakoff; MentionSubject: Re: [alpheios-project/pwa-prototype] inflection tables not appearing? (#48)that is bizarre. Do Greek nouns as well as verbs work?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106","url":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alpheios-project/pwa-prototype","title":"alpheios-project/pwa-prototype","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/alpheios-project/pwa-prototype"}},"updates":{"snippets":[{"icon":"PERSON","message":"@balmas in #48: that is bizarre. Do Greek nouns as well as verbs work?"}],"action":{"name":"View Issue","url":"https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [alpheios-project/pwa-prototype] inflection tables not appearing? (#48)",
"sections": [
{
"text": "",
"activityTitle": "**Bridget Almas**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@balmas",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"alpheios-project/pwa-prototype\",\n\"issueId\": 48,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"alpheios-project/pwa-prototype\",\n\"issueId\": 48\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/alpheios-project/pwa-prototype/issues/48#issuecomment-395544106"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343670945\n}"
}
],
"themeColor": "26292E"
}

**Comment by balmas** [comment]
Yes Latin nouns and verbs use different code than Greek verbs.

**Comment by balmas** [comment]
So @kirlat maybe we will need to send some debugging to the html console from renderInflections and displayInflections ?

**Comment by balmas** [comment]
this doesn't seem to be occurring anymore.
