### ISSUE TITLE
dev environment port forwarding

### ISSUE THREAD

**Issue by balmas** [alpheios-project/pwa-prototype#5]
The issue is that it's difficult to setup the nginx conf to forward all http traffic to https in a way that works for a dev environment which uses mapped ports.

I.e. the proper ngnix conf for redirecting this traffic is to use
`return 301 https://$host$request_uri;`

But if 443 is mapped to a dev port on the container host, this will fail.

I think the only solution to this might be to have a build process for the dev environment which uses variables to identify the port mappings and inserts these variables into the nginx conf file .

**Comment by balmas** [comment]
A simple approach might be to use environment variables for this, and to update the nginx.conf with the port information directly in the docker file. For some examples see https://vsupalov.com/docker-env-vars/

**Comment by kirlat** [comment]
Thanks for the article about env vars in Docker. It is very well written and I was really enjoying reading it!

However, it's still not clear to me what would be the best configuration in our case.
Right now we have the following mapping in `docker-compose.yml`:
          8020 (Host OS port) -> 80 (Docker container port)
          8120 (Host OS port) -> 443 (Docker container port)
With this, the following server block in the Nginx config
```
server {
    listen 80 default;
    listen [::]:80;
    server_name localhost;
    #access_log  off;
    #error_log   off;
    ## redirect http to https ##
    return 301 https://$host:8120$request_uri;
}
```
will redirect `http://localhost:8020` to `https://localhost:8120`. Everything works perfectly.

However, this is not what is expected from the PWA. Expected behavior is that a request to `http://pwadomain.com` would be redirected `https://pwadomain.com`. In our case, since we're using a custom port and a PWA URI is `https://localhost:8120` it is expected that a request to `http://localhost:8120` would be redirected to `https://localhost:8120`. Redirection to HTTPS should work for the exact URI of an app, but with no `s` in `https`.

With no custom ports speciied it works because of default ports: browser translates `http://pwadomian.com` to `http://pwadomain.com:80` and similarly it adds 443 for HTTPS. Those ports can then be remapped. However, it will not work for any custom ports as both HTTP and HTTPS requests are expected to have the same port (`s` in a protocol gets removed, no other parts of a URI are changed). I'm not sure if we can ever configure this with a custom port and Docker port mapping.

The only idea I have is to use `http(s)://localhost` with default ports as a URI for app testing. It might interfere with anything running on localhost, but I see no way how to configure it with custom ports. We could create a custom test domain to use with default ports and add it to the local hosts file, but then it would increase a complexity of configuration as this needs to be done differently on different OS and probably cannot be automated.

Do you have any ideas what would be the best config option here?

**Comment by kirlat** [comment]
That's how I understand it. In Lighthouse audit docs (https://developers.google.com/web/tools/lighthouse/audits/http-redirects-to-https) it says:

> Lighthouse changes the page's URL to http, loads the page, and then waits for the event from the Chrome Debugger that indicates that the page is secure. If Lighthouse does not receive the event within 10 seconds then the audit fails.

I take this as it changes nothing but replaces `https` with `http`.

**Comment by balmas** [comment]
this seems to me to be more of a limitation of the lighthouse testing tool than anything else.

However, I think we don't want to get too bogged down in this point. It seems probable to me that as the PWA technology matures this will be resolved.  I think for now I am inclined to just use the default ports (80/443) and deal with the potential conflicts in our development environments, so that we can focus on the Alpheios code itself.

**Comment by kirlat** [comment]
I'm thinking maybe we can continue using custom ports (as it is more convenient) and just ignore this test? When a PWA be deployed on a 'real' domain, we would be able to use default ports and configure a web server to do a redirect easily. This should satisfy this test.

To me, this test has nothing to do with the PWA itself (as long as redirection is not done within a PWA, but this is not recommended for reasons of performance), but rather tests a server configuration.

I think this test is probably not important for development of the PWA itself. What do you think?

**Comment by balmas** [comment]
Ok. I wasn't sure if that was preventing proper functioning of the worker or not.  In my environment the worker is not activated. But that might be a separate issue.  If this isn't blocking development then I agree it's not critical to address now.
